influxd: admin cacheloader continuous_querier filestore httpd logo metaclient monitor retention run shard snapshot store subscriber tsm
	cat admin > $@
	cat continuous_querier >> $@
	cat cacheloader >> $@
	cat filestore >> $@
	cat httpd >> $@
	cat logo >> $@
	cat metaclient >> $@
	cat monitor >> $@
	cat retention >> $@
	cat run >> $@
	cat shard >> $@
	cat snapshot >> $@
	cat store >> $@
	cat subscriber >> $@
	cat tsm >> $@
